# Generated by Django 2.1.7 on 2019-03-09 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 11, 45, 51, 619796, tzinfo=utc)),
        ),
    ]
